export const sliderItems = [
  {
    id: 1,
    img: "/assest/slider1.png",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "/assest/1.png",
    title: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "/assest/slider2.png",
    title: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "/assest/cat1.jpeg",
    title: "SHIRT STYLE!",
    cat: "shirt",
  },
  {
    id: 2,
    img: "/assest/cat2.jpeg",
    title: "LOUNGEWEAR LOVE",
    cat: "Tshirt",
  },
  {
    id: 3,
    img: "/assest/cat3.jpeg",
    title: "LIGHT JACKETS",
    cat: "coat",
  },
];
export const popularProducts = [
  {
    id: 1,
    title: "Herman T-shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/pro1.png",
    cat: "Tshirt",
    size: ["sm", "lg", "xl"],
    color: ["yellow", "pink"],
    createdAt: "2021-09-10T15:28:56.441",
    price: 111,
  },
  {
    id: 2,
    title: "Hermes T-shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/pro2.png",
    cat: "Tshirt",
    size: ["sm", "lg", "xl", "xxl"],
    color: ["gray", "lightgray"],
    createdAt: "2021-09-11T15:28:56.441",
    price: 12,
  },
  {
    id: 3,
    title: "Hawaii shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/pro3.png",
    cat: "shirt",
    size: ["xl", "xxl"],
    color: ["red", "darkblue", "green"],
    createdAt: "2021-09-11T15:38:56.441",
    price: 13,
  },
  {
    id: 4,
    title: "Hawaii dress",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/pro4.png",
    cat: "shirt",
    size: ["sm", "xl", "xxl"],
    color: ["darkblue", "green", "gray"],
    createdAt: "2021-10-11T18:38:56.441",
    price: 14,
  },
  {
    id: 5,
    title: "Purse",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/pro5.png",
    cat: "shirt",
    size: ["sm", "xl"],
    color: ["pink", "green", "gray"],
    createdAt: "2021-10-12T17:38:56.441",
    price: 15,
  },
  {
    id: 6,
    title: "Hat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/pro6.png",
    cat: "coat",
    size: ["sm", "xl", "xxl"],
    color: ["black", "green", "gray"],
    createdAt: "2021-10-12T19:38:56.441",
    price: 16,
  },
  {
    id: 7,
    title: "Socks",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/socks.png",
    cat: "coat",
    size: ["sm", "xl", "xxl"],
    color: ["pink", "green", "red"],
    createdAt: "2021-11-12T18:38:56.441",
    price: 17,
  },
  {
    id: 8,
    title: "Rainbow Coat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/coat.png",
    cat: "coat",
    size: ["lg", "xl", "xxl"],
    color: ["gray", "green", "black"],
    createdAt: "2021-11-12T20:38:56.441",
    price: 18,
  },
  {
    id: 9,
    title: "Tshirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/pro9.png",
    cat: "Tshirt",
    size: ["lg", "xl"],
    color: ["gray", "green", "black", "red"],
    createdAt: "2021-11-12T20:50:57.441",
    price: 19,
  },
  {
    id: 10,
    title: "Shoes",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta natus ullam at mollitia rerum numquam, praesentium impedit dolor enim, quisquam perspiciatis? Dolor voluptas velit placeat beatae quod sint pariatur. Optio?",
    img: "/assest/pro10.png",
    cat: "coat",
    size: ["lg", "xl"],
    color: ["gray", "black", "red"],
    createdAt: "2021-11-12T20:50:59.441",
    price: 2000,
  },
];
